### ISSUE TITLE
Schriftart und Abstände

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#1014]
Zur Zeit ist die Balance des Tools noch nicht ausgeglichen. Die Hierarchien der Webseite sind nur sehr schwer zu erkennen.

### Anforderungen
- Die Styles werden anhand der jeweiligen Tags definiert um die Einheitlichkeit zu garantieren.
- Die [Schriftart](https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=3040-1640&t=HJRRh2ZmSQTaARyv-4) ist in allen Browsern die gleiche.
- Die Abstände und grössen der Schrift entsprechen im Verhältniss dem definierten [Layout](https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=2919-21204&t=HJRRh2ZmSQTaARyv-4), dabei wird wahrscheinlich alles etwas grösser werden.
- Die Styles werden von UX kontrolliert und in Zusammenarbeit mit UX entwickelt.

### Akzeptanzkriterien
- [x] Die Styles sind konsequent durch das ganze Tool überarbeitet und entsprechen der Vorgesehenen Hierarchie
- [x] Testing ist angepasst
- [x] UX hat die Änderungen gereviewd
- [x] Pippo hat die Änderungen abgesegnet

**Comment by ManuelMoeri** [comment]
### ToDo:
- Der Test Should generate checkin list im 'checkIn.cy.ts' file wurde im Ticket https://github.com/puzzle/okr/issues/977 mit xit übersprungen da dieser nicht mehr Funktioniert hat. Sobald das Stying für alle überschriften implementiert wurde muss dieser test wieder eingebunden werden.

**Comment by ManuelMoeri** [comment]
### Stand 30.10.2024
Ich habe heute grundsätzlich mit dem Ticket angefangen. Einige styles habe ich bereits implementiert. Es bleibt trotzdem noch so viel mit Paco & UX abzusprechen.

**Fragen**
- In welchen Style sheets werden die jeweiligen Ebenen gestyled? (Overview = Styles, Detail = ?, Dialog = ?)
- Was war die mindest Grösse auf welche wir uns geiniget haben?
- Welches sind die neusten UX designes?

**Comment by ManuelMoeri** [comment]
### Stand 04.11.24 (Morgen)

Nach einem aufschlussreichem Gespräch mit Simu letze Woche habe ich immer noch eine Fragen und ToDos für Heute.

**ToDo**
- [ ] Headings auf dem Keyresult mit Paco besprechen
- [ ] Abklären der Grösse des check-in textes & confidence schriftzug mit UX
- [ ] Festlegen in welchen stylesheets die jeweiligen Ebenen gestyled werden  (Overview = Styles, Detail = ?, Dialog = ?)

**Comment by ManuelMoeri** [comment]
### Das Ticket ist currently auf **Blocked** da UX sich untereinander mit meiner Lösung der Schriftgrösse am absprechen ist.

**Comment by ManuelMoeri** [comment]
### Update 07.11.2024
Nach einem Meeting mit UX am 06.11.2024 ist der jetzige Stand ähnlich geblieben. Sie haben bei [Figma](https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=2916-561&node-type=canvas&t=nup1FQPcn5pycaNN-0) eine neue Notiz unten rechts mit ein paar Anmerkungen hinzugefügt.

Bezüglich der Schriftart haben sie mir mehr oder weniger freie Hand gelassen. Sie sagten mir das ich mal ein paar verschiedene Grössen konzipieren und mir von verschiedenen Personen feedback holen soll. Diese Personen sind Paco, Pippo und jemand anderes der das OKR oft verwendet.
