### ISSUE TITLE
Update Angular to 19

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#1070]
Update Angular auf version 19.

>  [!CAUTION]
> Currently `@angular-devkit/build-angular` can not be updated because of unmet peer deps in `jest-preset-angular` thus Angular > 19 can not yet be implemented!
> keep track on https://github.com/thymikee/jest-preset-angular/blob/b415b97ec1467a1384951158ea421e94b7e8fd78/package.json#L60
> neuer Release is in the making: https://github.com/thymikee/jest-preset-angular/blob/v14.4.0-rc.0/package.json
## Update
New version of jest-preset-angular is released

**Comment by nevio18324** [comment]
Die Version ist noch nicht von Angular supported.
Man könnte Jedoch das umgehen, was aber zu anderen Problemen führen könnte.

**Comment by nevio18324** [comment]
### Todo's  ###

- [ ] [Migration guide](https://angular.dev/update-guide?v=18.0-19.0&l=1)  durchlesen 
- [ ] Angular Core und Cli updaten
- [ ] alle anderen dependencies falls nötig z.B Angular Material
- [ ] falls nötig devDependencies updaten
- [ ] nach Deprecations schauen/lösen
- [ ] Das standart für standalone ist in der neuen Version true was bei uns nicht der Fall ist heisst bei allen component,pipes und directives  standalone = false hinzufügen
- [ ] Man soll beim variablen access im template nicht mehr this brauchen heisst z.B {{this.foo}} -> {{foo}} um änderen

**Comment by nevio18324** [comment]
#### Muss noch peer-reviewed werden. ####

**Comment by nevio18324** [comment]
#### Ausversehen geclosed

**Comment by nevio18324** [comment]
### Blocked ###
Das Ticket wird geblocked da Jest 29.7.0 4 deprecated peer dependencies besitzt
```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory.
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException instead

```
Glob und inflight werden in Jest 30.0.6-alpha gelöst jedoch braucht angular-devkit/build-angular jest 29.7.0
Auf github gibt es schon mehrere issues über dieses Problem
https://github.com/jestjs/jest/issues/15087
https://github.com/jestjs/jest/issues/15236
jedoch scheint Jest dies erst in der Version 30 lösen zu wollen. Bis dahin müssen wir warten,
