### ISSUE TITLE
Deployment von Alignment.

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#1116]
Lias hat im Rahmen seiner IPA einen POC für das Allignment erstellt. 
Wir wollen nun Testen, ob dieser den Anforderungen an das Tool gerecht wird.

### Anforderungne
- Die IPA von Lias ist deployed
- Die IPA von Lias kann einem Stakeholder Präsentiert werden, sodass wir analysieren können was bereits erfüllt ist und was noch angepasst werden muss.

### Akzeptanzkriterien
- [x] Ready for review durch stakeholder
- [x] Es muss noch nicht sauber getestet sein
- [x] Es müssen noch nicht alle bugs behoben worden sein.

**Comment by nevio18324** [comment]
### Vorgehen ###

- [ ] Auf dem Branch die Applikation starten
- [ ] falls funktioniert Präsentation erstellen für Stakeholder.

**Comment by kcinay055679** [comment]
Ich habe die PR von Lias rebased und in einen Lauffähigen Zustand gebracht. 
Diverse Tests failen noch aber dies ist für das deployment nicht relevant.
Das Deployment kann auch mit failenden Tests erstellt werden

**Comment by nevio18324** [comment]
### Todo's ###

- [ ] Das Programm zum laufen zu bringen
- [ ] Ein Deploy image erstellen
- [ ] Das Image ins registery legen
- [ ] Mit Minder weiterschauen

**Comment by nevio18324** [comment]
### Stand 19.11 ###
Die Applikation läuft jedoch funktioniert das Network feature nur bei metrischen key-results und nicht bei ordinalen key-results

**Comment by nevio18324** [comment]
### Stand 21.11 ###
Ich habe nun auf openshift unter okr-staging ein Pot eröffnet welcher das Alignment beinhaltet es sollte einwandfrei funktionieren.
