### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#1135]
Der Formatter für frontend ist noch nicht optimal

### Anforderungen
-  Der Formatter für frontend ist angepasst nach Absprache mit Paco
-  Der Formatter für das Backend ist angepasst nach dem Formatter vom UniLu Projekt
-  Der githook wurde angepasst
-  In  den Pipelines wird mithilfe des neuen Formatters nur noch validated und nicht mehr die formatten changes auf main gepushed 
- Eclipse formatter docs [https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html)
### Akzeptanzkriterien
- [ ] Alle Anforderungen wurden erfüllt

**Comment by kcinay055679** [comment]
The backend formatter uses now spotless with the config of unilu
TBD
Fix frontend formatter

**Comment by kcinay055679** [comment]
Wir entschieden uns auch im frontend für spotless. Dies muss aber noch richtig konfiguretiert werden

**Comment by Miguel7373** [comment]
### TODO

- [ ] Fix Error of Property loading
- [ ] Frontend config richtig konfigurieren
- [ ] Run formatter.

**Comment by Miguel7373** [comment]
Added second branch to resolve the formatting changes

Still Todo
- [ ] ESLint formatting changes refactoring in this PR (https://github.com/puzzle/okr/pull/1179)

**Comment by kcinay055679** [comment]
Miguel has apparantly not pushed his changes. Doesn't make any sense to work on this without them

**Comment by RandomTannenbaum** [comment]
**Stand 22.11.2024**
Ich habe nochmal angeschaut was für rules noch failen und diese gefixt die einfach waren. Den Rest ist nun excluded und wird in einem Folgeticket behandelt. Momentan failen noch die frontend tests. Diese muss man noch fixen.

Das Ticket ist auf zwei PRs aufgeteilt (beide mit diesem Ticket verknüpft). Die formatter PR hat nur die Konfiguration ohne das angewendete formatting. Die apply formatting PR baut auf diese PR auf und applied das formatting auch noch. So kann man die changes einfacher ansehen.

ToDo:
- [ ] Frontend-Tests auf dem geformatteten branch fixen.
- [ ] Folgeticket erfassen
- [ ] Wenn Format und config approved sind den geformatteten Branch in den Branch mit den configs mergen (dann sollten auch alle Tests wieder durchlaufen insofern man sie auf dem geformatteten Branch gefixt hat) und dann in main mergen.

**Comment by Miguel7373** [comment]
Für dieses Ticket existieren 2 PR's

[1159-formatter](https://github.com/puzzle/okr/pull/1159)
Die PR hat das Config-File enthalten und solle erst gemerged werden, wenn die untere PR in diese gemerged wurde.

[1159-formatter-applyed](https://github.com/puzzle/okr/pull/1159)
Diese PR enthält die changes des formatters und sollte in die obere PR gemerged werden, sobald die config approved wird.

**Comment by RandomTannenbaum** [comment]
**Zusatz**
Nach anpassen der eclipse formatter config wie in der PR beschrieben soll auf dem Skills eine PR erstellt werden, in der die angepasste formatter config auch dort übernommen wird.
