### ISSUE TITLE
Pipes überarbeiten.

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#1136]
Nurnoch da Pipes wo sinnvoll. Nur noch eine Transformpipe.

### Anforderungen
- `parse-unit-value.pipe.ts` wird nur in einem Typescriptfile verwendet, deshalb sollte dies eine helper function im entsprechenden ts werden.
- Die restlichen pipes können vermutlich zu einer pipe zusammengefasst werden
- Testing ist aktuallisiert

### Akzeptanzkriterien
- [ ] Pipes sind überarbeitet
- [ ] Testing ist ergänzt

**Comment by MasterEvarior** [comment]
### Stand 13.11.24
Es gibt nun nur noch eine Pipe. Eine wurde durch eine Helper-Methode ersetzt, die anderen zwei zu einer einzelnen zusammengefasst. Unit-Tests wurden für beide geschrieben, könnten aber evtl. noch ergänzt werden. Der ` this.keyResult.keyResultType === 'metric'` check im ` check-in-form.component` ist noch etwas unschön. Dort muss man prüfen ob es möglich ist das direkt dem zuständigen Metric-Form abzugeben.  

**TODO:**
- [ ] Tests für ` check-in-form` ergänzen
- [ ]  Prüfen ob die `parseUnitValue`-Methode zu ` check-in-form-metric` verschoben werden kann.

**Comment by MasterEvarior** [comment]
## Stand 15.11.24
Der `this.keyResult.keyResultType === 'metric'` check konnte mithilfe einer eigenen Directive in den `check-in-form-metric.component.ts` verschoben werden. Dafür mussten einige Unit-Tests angepasst werden. 

PR ist offen und assigned.

**Comment by MasterEvarior** [comment]
### 20.11.24
Heute noch die Verbesserungen aus dem PR implementiert und dann gemergt.
