### ISSUE TITLE
Naming cleanup

### ISSUE THREAD

**Issue by RandomTannenbaum** [puzzle/okr#1171]
Momentan haben wir im tool sehr unterschiedliche naming conventions. Dazu gehören zum Beispiel Java-Klassen, Variablen, CSS-IDs und Klassen usw. Mit diesem Ticket soll das Naming im gesamten Ticket vereinigt werden.

Für das naming kann man sich hier orientieren, es sollte jedoch hier ein einheitliches naming dokumentiert werden, bevor man mit dem Ticket beginnt: https://codimd.puzzle.ch/VelTcGoRSRGyd8hFHpadjw#.

**Naming conventions**
- Frontend
  - CSS: Kebab-Case
  - Cypress: Testfiles sind `test-name.cy.ts`,
  - Assets sollen in ihrer Kategorie konsisten sein (z.B. alle `/images` im Kebab-Case )
  - Alles sonst [Angular conventions](https://angular.dev/style-guide#general-naming-guidelines)
- Backend
  - Properties im Kebab-Case
  - Alles sonst gemäss [Java-Conventions](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)

**Aktzeptanzkriterien**
- [x] Naming-Richtlinien sind im Codi dokumentiert
- [x] Frontend
  - [x] CSS-Naming ist gemäss oben umgesetzt
  - [x] Alle Angular-Files sind gemäss [Convention](https://angular.dev/style-guide#symbols-and-file-names) genannt
  - [x] Alle Angular-Componenten sind Pascal-Case und enden mit  `Component`,  i.e. `MyCoolComponent` 
  - [x] Alle  Angular-Services sind Pascal-Case und enden mit `Service`, i.e. `MyCoolService`  
  - [x] Alle Angular-Pipes sind Pascal-Case und enden mit `Pipe`, der Pipe-Name selber ist lower CamelCase 
  - [x] Alle Methoden sind lower Camel-Case
  - [x] Alle Konstanten (analog `private final static` in Java ) sind upper Snake-Case 
  - [x] Alle Enums folgen der [Convention von TS](https://www.typescriptlang.org/docs/handbook/enums.html)
  - [x] Alle Cypress-E2E-Test-Files sind gemäss oben definiert benannt
  - [x] Cypress-Files halten sich an die selber Conventions wie sonst fürs Frontend gelten, soweit möglich
  - [x] Assets sind pro Kategorie konsistent
- [x] Backend
  - [x] Alle Konstanten sind (`private final static`) sind upper Snake-Case
  - [x] Alle Packages-Names sind lowercase
  - [x] Alle Klassen-Namen sind Pascal-Case
  - [x] Alle Methoden sind lower Camel-Case
  - [x] Alle Variablen sind lower Camel-Case (Konstanten ausgenommen)
  - [x] Alle Properties sind Kebab-Case

**Comment by RandomTannenbaum** [comment]
**Vorgehen**
- [ ] Alle nötigen naming conventions und custom Klassennamen in einem codi erfassen, sowie offizielle styleguides suchen und auch im codi verlinken.
- [ ] Im Backend beginnen und Ordner für Ordner durchgehen. Wenn ein file angepasst wurde evtentuelle zusätzliche namings im Codi erfassen.
- [ ] Jeden abgeschlossenen Ordner im Codi erfassen um den Fortschritt zu tracken. Wenn mitten in einem Ordner aufgehört wird diesen vermerken, sowie das letzte File an dem gearbeitet wurde.
- [ ] Am Ende jeden Tages kurz mit jemand anderem den Fortschritt und die erarbeiteten naming conventions besprechen.
- [ ] Das gleiche im frontend wiederholen.

**Comment by RandomTannenbaum** [comment]
Codi mit naming conventions:
https://codimd.puzzle.ch/DWVLjwB8SkaCw0-0LbREWg?edit

**Comment by RandomTannenbaum** [comment]
**Stand 25.11.2024**
Für den momentanen Stand des refactorings siehe codi.

**Comment by Miguel7373** [comment]
### Todo Frontend Naming Config

- [ ] Dokumentation zu den verschiedenen Tools lesen
- [ ] Bestes Tool für uns auswählen
- [ ] Config für CSS schreiben
- [ ] Config für HTML schreiben
- [ ] Config für Ts schreiben
- [ ] Config für Exceptions schreiben
- [ ] Testen, ob jede convention richtig checkt
- [ ] Peer-Review

**Comment by Miguel7373** [comment]
### Stand 9.12.24

Ich habe mich nun für eine reine ESLint Lösung entschieden, da es einfach weniger dependency
 sind und wenn auch komplizierter als mit anderen Tools wie Stylelint ist es trotzdem noch im akzeptablen Bereich
Ich habe nun begonnen, die ESLint config für TS Files zu schreiben. Habe aber noch keine gute Möglichkeit gefunden, die Custom Wörter wie KeyResult auf richtige Trennung oder Schreibweise zu testen.

**Comment by Miguel7373** [comment]
### Stand 10.12.2024

Ich habe nun weiter an der Config gearbeitet. Ich habe bei html und ts die grundlegenden regeln die gecheckt werden eingebaut.

Still Todo
- [ ] Bei Ts muss noch ein weg gefunden werden wie readonly variablen nicht beachtet werden da beim check nach camel case readonly variaben in UPPER_CASE als falsch angesehen werden
- [ ] SCSS Config
- [ ] Bie allen muss nocht die ausnahmen (Keyresult/TeamManagement...  https://codimd.puzzle.ch/DWVLjwB8SkaCw0-0LbREWg?edit ) richtig configuriert werden

**Comment by RandomTannenbaum** [comment]
**Stand 11.12.2024**
Das Backend habe ich jetzt fertig bearbeitet und gehe nun zum frontend über.

**Comment by Miguel7373** [comment]
### Stand 12.12.2024


Ich habe weiter an der config gearbeitet. Ich habe die Parcing Errors rausgenommen, damit nur noch die Naming conventions angezeit werden. Ebenfalls habe ich es geschafft, dass die readonly variablen nicht mehr als Fehler angezeigt werden, wenn sie in UPPER_CASE sind. Ich habe dann noch an dem id-matcher gearbeitet, damit wir garantieren können, dass die custom Wörter richtig sind. Der regex geht leider nicht mit der i flag da es eine Version der regexe ist, wo es noch kein caseinsensitive supportet (nicht so wie ich es geschrieben habe)

**Comment by ManuelMoeri** [comment]
### Tests mit @DisplayName versehen

Hier sind alle Ordner der Tests aufgelistet welche diese Annotation erhalten sollen:
- [ ] architecture
- [ ] controller
- [ ] deserializer
- [ ] mapper
    - [ ] checkin
    - [ ] keyresult
- [ ] models
    - [ ] authorization
    - [ ] keyresult
- [ ] multitenancy
    - [ ] customization
- [ ] security
    - [ ] helper
- [ ] service
    - [ ] authorization
    - [ ] business
    - [ ] clientconfig
    - [ ] persistence
    - [ ] validation
- [ ] util.quarter
    - [ ] check
    - [ ] generate
        - [ ] h2

Alleinstehende files:
- [ ] ForwardFilterTest
- [ ] SpringCachingConfigTest
- [ ] UserKeyGeneratorTest

**Comment by RandomTannenbaum** [comment]
**Stand 18.12.2024**
Ich habe das Ticket gestern noch gerebased und heute am frontend weitergearbeitet. Neben den ganzen Cypress sachen, habe ich einen grossteil der components in `/components` abgeschlossen (siehe codi für genauen Fortschritt).
