### ISSUE TITLE
Re-enable ESLint rules

### ISSUE THREAD

**Issue by Miguel7373** [puzzle/okr#1209]
Im Ticket [#1135](https://github.com/puzzle/okr/issues/1135) wurde ESLint eingeführt. Nun hat es im Winter ein paar rules, die noch aufgeschaltet wurden, da sie nicht das formatting betreffen. Die müssen jetzt gelöst werden.
Gehe dafür auf einen seperaten branch ausgehend von feature/1135/formatter und deaktiviere zuerst das stylistic plugin. kommentiere danach alle regeln aus, so das nur noch die .ts Regeln ausgeführt werden.
Führe danach  `npm run lint:format` aus. Commite diesen Stand, dies wird als grundlage dienen.
Optimalerweise sollte `npm run lint` nun keine Fehler mehr ausweisen.
Aktiviere nun nacheinander die deaktivierten Reglen und löse die damit verbundenen Probleme.

Orientiere dich dafür an den Kommentaren

Im *eslint.config.mjs* sind die regeln.

To rebase the branch rebase onto the 1135/formatter branch (or onto main if the branch is already merged)
for 

### Anforderungen

- Es wurden alle rules von *ToDO:* bis zu den *stylistic rules* entfernt

### Akzeptanzkriterien

- [x] Die rules unter dem ToDO existieren nicht mehr.
- [x] Der formatter läuft durch.

**Comment by nevio18324** [comment]
### Todo's ###

- [ ] Stylistic plugin deaktivieren
- [ ] npm run lint:format ausführen dannach den state pushen
- [ ] (Optional falls nicht zu viel Zeit benötigt) Soll npm run lint keine errors melden
- [ ] Dannach von oben nach unten die Regeln aktivieren und die beschriebenen Probleme lösen
