### ISSUE TITLE
Schriftgrösse und stärke

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#1227]
Zur Zeit sind einige Schriften nicht bold, welche aber bold sein sollten.

- Textfelder in Dialogen: Confirm, Check-in, ...
- Sidepanel Titel der Abschnitte sollten bold sein. 

> [!TIP]
> Wurde bereits mit  @ManuelMoeri besprochen

### TODO
- [x] Schriftgrösse & Stärke an folgenden Stellen überprüfen:
  - [x] Overview (Objective, KeyResult, Teams usw.)
  - [x] Objective detail
  - [x] KeyResult detail
  - [x] Dialoge:
    - [x] Objective erfassen / bearbeiten
    - [x] KeyResult erfassen / bearbeiten
    - [x] Check-in erfassen / bearbeiten
    - [x] Objective abschliessen
    - [x] Objective duplizieren
    - [x] Objective als draft speichern / eröffnen
    - [x] Check-in history
    - [x] Team erfassen / bearbeiten
    - [x] Member registrieren
    - [x] Confirm dialog
  - [x] Overview der Teamverwaltung
  - [x] Team detail
  - [x] Member detail
- [x] Peer review 

### Akzeptanzkriterien
- [x] Styling ist richtig umgesetzt
- [x] Testing ist wo sinnvoll ergänzt

**Comment by ManuelMoeri** [comment]
### 09.12.2024

**Abkzuklärende Schriftzüge**
- [ ] Objective hinzufügen -> weight
- [ ] KeyResult hinzufügen -> weight
- [ ] Action plan punkte -> weight
- [ ] Check-in history -> weight & size
- [ ] Team erfassen -> weight
- [ ] Member registrieren -> weight

**Comment by ManuelMoeri** [comment]
### Review Minder
- [ ] KeyResult detail: Confidence schriftzug überprüfen
- [ ] KeyResult hinzufügen button anschauen
- [ ] User detail: Buttons zu fett
- [ ] Objective abschliessen:  Text in buttons zu fett
