### ISSUE TITLE
Konsistentes Farbschema der buttons

### ISSUE THREAD

**Issue by ManuelMoeri** [puzzle/okr#1238]
**Describe the bug**
Der bug tritt bei dem 'Speichern' button einiger Dialog auf. Diese buttons haben das falsche Farbschema.

**To Reproduce**
1. Besuche pitc.okr.localhost:4200 oder acme.okr.localhost:4200
2. Drücke auf das Drei Punkte menü eines beliebigen Objectives.
3. Wähle die Option 'Objective Duplizieren aus.
4. Der 'Speichern' button auf dem Dialog erscheint in der secondary anstatt der primary Farbe.

**Expected behavior**
Buttons die als Haupt-action dienen sollten immer die primary Farbe erhalten. -> **Mit UX klären**
Dies soll über das ganze Tool hingweg konsistent sein -> Checken und allenfalls beheben ob dies noch anderen orten auftritt.

**Screenshots**
Falsch
![Image](https://github.com/user-attachments/assets/0f99d9c2-41c7-44cc-9a8c-dc21bc765527)

Richtig
![Image](https://github.com/user-attachments/assets/80d41849-7d72-456c-af3d-ea624330df3f)

**Additional context**
Ob wirklich jeder Speichern button primary colors erhalten soll, sollte noch mit UX geklärt werden. Meines wissens nach schon.

**Comment by ManuelMoeri** [comment]
### 15.01.2025
**ToDo**
- [ ] Ticket lesen
- [ ] Applikation nach fehlern durchkämmen & hier Dokumentieren
  - [ ] X
  - [ ] Y
  - [ ] Z
- [ ] Unklarheiten mit UX absprechen
- [ ] Tests schreiben
- [ ] Smoke tests
- [ ] :heavy_check_mark:

**Comment by ManuelMoeri** [comment]
### Stand 20.01.2025
Heute habe ich nebst den Meetings weiter daran gearbeitet die Tests zu schreiben. Bei diesen habe ich die E2E Tests für alle KeyResult und Objective dialoge beendet. Was noch zu tun ist, sind die Dialoge rund um die Check-ins und sämtliche Dialoge bezüglich der Teamverwaltung. Um einfacher auf primary buttons zu überprüfen habe ich eine funktion namens `checkForPrimaryButton` implementiert. Diese ist zum teil in den verschiedenen Dialogen mit unterschiedlichen test-ids zum klicken implementiert aber im Grundsatz gleich.

**TODO**
- [ ] E2E Tests Check-ins
- [ ] E2E Tests Teamverwaltung
- [ ] Cleanup
