### ISSUE TITLE
OKR-Backend reformatieren der Check-in

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#307]
Als **Kunde** möchte ich, mittels Check-in, den Fortschritt eines Key Results erfassen und diesen repräsentativ in der Datenbank abspeichern.

### Anforderungen
- Das Model der Measures heisst neu Check-In und ist wie im Klassendiagram beschrieben umgesetzt, Action gehört _**nicht**_ zu dieser Story.
- Die Records, Mapper, Repositories, Services und Controller sind angepasst und erüllen die Definition der REST-Schnittstelle.
- Die Validierung ist wie anhand des Beispiels beim Team umgesetzt.
- Die Änderungen an der Datenhaltung ist mittels Migrationsskript umgesetzt. 
- Für bestehenden Daten nach altem Datenbankschema ist die Funktionalität der Applikation weiterhin gewährleistet.
- Anstelle von **Kommentar**  bleiben **Veränderungen seit letztem Check-in** und **Massnahmen** bestehen.

### Hinweis
- Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist sowohl das Klassendiagram, wie auch die Definition der Restschnittstelle aufzufinden.  
-  Weiter sind im [Figma](https://www.figma.com/file/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?type=design&node-id=351-12091&mode=design&t=ZQk9GfxYSrS8YVeN-0) die Zusammenhänge zwischen den Komponenten ersichtlich. 
-  Da beim Check-In neu eine Abstrakte Klasse verwendet wird um beide Arten von Key Results darzustellen verwenden wir neu die [Single-Table-Strategy](https://thorben-janssen.com/complete-guide-inheritance-strategies-jpa-hibernate/) von Hibernate. Ein weiteres [Beispiel](https://dzone.com/articles/introduction-spring-data-jpa-inheritance-rest-app) für die Single-Table-Strategy. 
- Auch das [Builder-Pattern](https://dev.to/karthikrg/implementing-builder-pattern-abstract-class-3c1l) soll abstrahiert werden. 

### Akzeptanzkriterien
- [x] CheckIn ist auch beim KeyResult Controller angepasst 
- [x] CheckIns werden glöscht, wenn KeyResult gelöscht wird
- [x] Änderungen am Datenbankschema sind in **_einem_** Migrationsskript umgesetzt.
- [x] Die Unit und IT-Tests sind nachgezogen mit minimum 80% Testabdekung
- [x] Smoke Tests wurden gründlich durchgeführt
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
_Anpassungen sind mit Paco vorab zu besprechen und an dieser Stelle zu dokumentieren_

### Vorgehen
- [x] Auf Main Branch gehen
- [x] Feature Branch mit Ticketnummer erstellen
- [x] Controller / Schnittstelle anpassen (hierzu Dokumentation einsehen)
- [x] Nicht benötigte Methoden löschen, nicht benötigte Tests löschen (BusinessService)
- [x] ServiceStruktur übernehmen (PersistenceService, BusinessService, ValidationService)
- [x] Klassenstruktur umsetzen
- [x] Migrationsskript erstellen
- [x] Neue Models in Mapper, Helper, etc. einsetzen
- [x] MeasureModel überarbeiten
- [x] Validation umsetzen
- [x] Tests mit Coverage laufen lassen, nicht abgedeckte Methoden testen
- [x] Smoke Testen
- [x] Draft Pullrequest erstellen
- [x] File Changes überprüfen
- [x] Rieview von @peggimann  oder @tuxmatta  einfordern
- [x] Review changes umsetzen (wenn vorhanden)

**Comment by MarcEgliP** [comment]
# Aktueller Stand des Tickets
- CheckIn ist in BusinessService, ValidatorService und PersistenceService implementiert
- Migrationsfile wurde erstellt
- Models und DTOs wurden erstellt sind fertig

# Todo
- Measure aus Overview Model und Service entfernen
- Migrationsfile überarbeiten name="V2_0_3_checkInRefactoringDropAttrsAddNew.sql", nach Beispiel von @lkleisa umsetzen, siehe Branch #361 
- Tests fixen und refactoren
