### ISSUE TITLE
Okr - Erstellen eines Action plans

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#319]
Als **Kunde** möchte ich bei meinen Key Results zusätzlich zu den Metriken wie ich dieses quantifiziere auch einen Action Plan festhalten, damit ich weiss, wie ich das Ziel erreiche.

### Anforderungen
- Für die Key Results kann ein Actionplan erfasst werden
- Standardmässig wird beim Erfassen der Key Results 3 Listeneinträge für Action Plan dargestellt
- Weitere Listeneinträge können hinzugefügt werden
- Die Listeneinträge können verschoben werden
- Bei einem Check-in kann der Actionplan ausgefüllt werden
- Bei dem Key Result Detail wird der Actionplan dargestellt und es ist ersichtlich welche Tasks erfüllt sind und welche nicht
- Die Reihenfolge wird im Backend abgespeichert, damit diese immer der korrekten Reihenfolge im Frontend entspricht
- Im Backend ist eine neue Tabelle angelegt, welche einen Actionplan halten kann.

### Hinweis

![Image](https://github.com/puzzle/okr/assets/113369749/4436c704-2c43-42e5-856b-7975db940973)

![Image](https://github.com/puzzle/okr/assets/113369749/9af1091b-5c24-4179-bf40-738d97834110)

- Im [Auftrag](https://codimd.puzzle.ch/s/LhSU-jpJH#) ist sowohl das Klassendiagram, wie auch die Definition der Restschnittstelle aufzufinden.  

### Akzeptanzkriterien
- [x] Ein Migrationsskript ist für das Backend erstellt.
- [x] Die Funktionalität ist mit Unit und IT-Tests getestet. 
- [ ] Angular Komponente und das Template sind mit Jest getestet
- [ ] Smoke Tests wurden gründlich durchgeführt
- [x] Die benötigten Daten werden mittels Service + RxJS geladen.
- [x] Dokumentationen sind nachgezogen
- [x] Die Story ist wie beschrieben umgesetzt

### Anpassungen an der Story
- Angular Material DragDrop macht genau das: https://material.angular.io/cdk/drag-drop/examples#cdk-drag-drop-connected-sorting-group
- Die Reihenfolge wird mit einem int im Backend gespeichert

### Vorgehen
- [x] Backend:
  - [x] Model
  - [x] Table
  - [x] Controller
  - [x] 3 Services
  - [x] KR Service: On Delete -> Delete all actions
  - [x] Update action mehrere auf einmal
  - [x] KeyResult Transiet actionList
  - [x] Actions erstellen bei createKeyResult()
  - [x] Action updaten wenn KeyResult type geändert wird
  - [x] Updaten bei updateKeyResult()
  - [x] KeyResult.actionList nicht null sondern []
  - [x] Authorization in backend einfügen 
  - [x] Testing (rest)
  - [x] Testing (ValidationService, PersistenceService, ActionControllerIT fixen)
- [ ] Frontend:
  - [x] Service
  - [x] Component
    - [x] Darstellung von Component
    - [x] Einbauen in KeyResult Dialog
    - [x] Action Array updaten auf actionText Array
    - [x] ActionPlan mit KR mitsenden bei create
    - [x] ActionPlan laden bei update
    - [x] Löschen implementieren
    - [x] CheckBox einbauen in CheckIn Dialog
    - [x] Checkboxen richtig speichern 
    - [x] Service richtig callen
    - [x] Nicht löschen wenn abbrechen button
    - [x] Cursor Pointer für delete Button
    - [x] Priority setzen bei create & updaten
    - [x] Bug wenn Element nach Namen setzen direkt verschoben wird
    - [x] Element aus Liste entfernen, wenn man es löscht
    - [x] Fix error in console
    - [x] CheckIn erfassen -> grauer Hintergrund bei Action Points
    - [x] Priority von DragDrop 
  - [ ] Testing

**Comment by lkleisa** [comment]
# Stand Montag Abend
- Das Backend ist soweit fertig, alles nötig wurde aus meiner Sicht erstellt (sollte aber noch geprüft werden)
- Den Component und Serivce habe ich im Frontend erstellt
- Der Serivce hat alle nötigen Methoden 
- Im Component habe ich das Material DragDrop eingebaut
- Bei Veränderungen wird die Position im Array **actionPoints** geändert
- Auch wenn das Input Field geändert wird, wird der neue Text an der richtigen Array Position gewechselt

## TODO 
- [ ] Das Material DragDrop ist nicht ganz so schön und nicht so wie im Figma -> Entweder so anpassen wie im Figma mit Space nach unten, oder eine andere Libary finden, welche besser ist
- [ ] Den Component auf den KeyResult Dialog on create einbauen
- [ ] Bei Edit von KeyResult
