### ISSUE TITLE
Usertests durchführen

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#476]
### ToDo

- [ ] Testskript und Szenarien schreiben
- [ ] Testpersonen und Termine organisieren (Personenauswahl siehe unten)
- [ ] ...
- [ ] Profit

### Ziel der Tests
_Als User möchte ich mit der Applikation die gewünschten Objectives und Key Results einwandfrei erfassen können. Damit dies möglich ist, wollen wir mit Usertests herausfinden, ob die Applikation dies auch erlaubt._

Ziele:
- Validierung der Lösung (Wie gut funktioniert das, was wir gebaut haben?)
- Identifikation von Schwachstellen (Welche Probleme treffen die User an bei der Erledigung ihrer Aufgaben)

### Organisation

- 5 Testpersonen, aus dem Kreis der zukünftigen User:
-- Adrian Berteletti
-- Adrian Brunner 
-- Philipp Leimgruber
-- Bruno Santschi
-- Mathias Krebs
- 1 Moderator: Entweder Simon oder Tobias
- 1 Beobachter: TBD
- Test-Environment: Stabile Umgebung mit vorbereiteten Teams/Objectives/KRs usw. definiert gemäss Test-Skript
- Test-Skript: Szenario und Aufgaben für die User
- Incentives
- Test-Räume und Termine organisieren

### Test-Inhalte
Die Hauptfunktionen der Lösung sollen getestet werden:

- Hinzufügen von Objectives, Key Results & Check-Ins
- Auslesen von Informationen über die Zielerreichung

### Nachbereitung
Nach den Tests werden die Erkenntnisse ausgewertet: Es werden die grössten Schwachstellen bestimmt und mögliche Verbesserungen definiert.

### Anforderungen

- TBD bei Ux

### Akzeptanzkriterien

- [ ] Alle verbesserungen sind in einzelnen Tickets erfasst und bereit für die Implementation

**Comment by shirsbrunner** [comment]
### Geplanter Grobablauf
Erläutern (finden / lesen) eines bestehenden Objectives
Erstellen eines Objectives
Erstellen eines Keyresults
Checkin Keyresult
Abschluss Objective
