### ISSUE TITLE
E2E Test Objective - CRUD

### ISSUE THREAD

**Issue by lkleisa** [puzzle/okr#548]
Teste die CRUD Operationen + Duplizieren vom Objective

### Todo
- [x] Objective Erstellen
- [x] Objective Detail
- [x] Objective bearbeiten
- [x] Objective Duplizieren
- [x] Objective Löschen

Dabei sind pro flow die folgenden Punkte zu beachten:
- [x] Darstellung der einzelnen Komponenten entsprechen dem Figma
- [x] Werden die Richtigen aktionen aufgerufen
- [x] Haben die Buttons die korrekte funktionalität
- [x] Werden die richtigen Dialoge geöffnet
