### ISSUE TITLE
E2E Test Objective - Functionality

### ISSUE THREAD

**Issue by lkleisa** [puzzle/okr#549]
Teste die Funktionalitäten vom Objective

### Todo
- [x] Objective auf der Overview vorhanden
- [x] Objective Freigeben
- [x] Objective Abschliessen
- [x] Objective Wiedereröffnen
- [x] Suchen nach Objectives
- [x] Unabhängig von Quartal

Dabei sind pro flow die folgenden Punkte zu beachten:
- [x] Darstellung der einzelnen Komponenten entsprechen dem Figma
- [x] Werden die Richtigen aktionen aufgerufen
- [x] Haben die Buttons die korrekte funktionalität
- [x] Werden die richtigen Dialoge geöffnet
