### ISSUE TITLE
E2E Test Key Result

### ISSUE THREAD

**Issue by lkleisa** [puzzle/okr#550]
Teste alles vom Key Result

### Todo
- [x] Key Result Erstellen
- [x] Key Result Detail
- [x] Action Plan
- [x] Key Result bearbeiten
- [x] Key Result Löschen

Dabei sind pro flow die folgenden Punkte zu beachten:
- [x] Darstellung der einzelnen Komponenten entsprechen dem Figma
- [x] Werden die Richtigen aktionen aufgerufen
- [x] Haben die Buttons die korrekte funktionalität
- [x] Werden die richtigen Dialoge geöffnet
