### ISSUE TITLE
E2E Test Check-in + Team Filter

### ISSUE THREAD

**Issue by lkleisa** [puzzle/okr#551]
Teste alles vom Check-in und den Team Filter

### Todo
- [x] Check-in Erfassen
- [x] Check-in in Liste Ansehen
- [x] Check-in bearbeiten
- [x] Confidence setzen
- [x] Teams in filter an/abwählen
- [x] Team Filter sollte in URL vorhanden sein

Dabei sind pro flow die folgenden Punkte zu beachten:
- [x] Darstellung der einzelnen Komponenten entsprechen dem Figma
- [x] Werden die Richtigen aktionen aufgerufen
- [x] Haben die Buttons die korrekte funktionalität
- [x] Werden die richtigen Dialoge geöffnet

**Comment by lkleisa** [comment]
## Stand Montag 13.11
Es sind alle Tests fertig und die meisten funktionieren auch. Jedoch gibt es noch ein Bug, mit dem Confidence Slider. Egal wie ich es probiert habe, cypress hat den Slider nur um eine Position nach Rechts geschoben. Ich habe mich mit Paco geeinigt, dass es okey ist wenn wir Confidence 4, 5 und 6 testen. 
### TODO
- [ ] Tests so anpassen dass sie laufen
  - [ ] Slider so bewegen können, dass er nach links get
  - [ ] Evt. wird eine andere Möglichkeit gefunden, mit welcher man auch mehrere Positionen schieben kann
### Info
- Ich habe 2 Möglichkeiten, eine ist auskommentiert. Diese dann bei fix auch löschen
