### ISSUE TITLE
E2E Test Scoring

### ISSUE THREAD

**Issue by lkleisa** [puzzle/okr#552]
Teste die Funktionalitäten vom Scoring Component auf Key Result Detail und Overview

### Todo
- [ ] Der Balken passt sich bei jeder metrischen Eingabe korrekt auf Key Result Detail an
- [ ] Der Balken passt sich bei jeder metrischen Eingabe korrekt auf der Overview an
- [ ] Der Balken passt sich bei jeder ordinalen Eingabe korrekt auf Key Result Detail an
- [ ] Der Balken passt sich bei jeder ordinalen Eingabe korrekt auf der Overview an

Dabei sind pro flow die folgenden Punkte zu beachten:
- [ ] Darstellung der einzelnen Komponenten entsprechen dem Figma
- [ ] Werden die Richtigen aktionen aufgerufen
- [ ] Haben die Buttons die korrekte funktionalität
- [ ] Werden die richtigen Dialoge geöffnet

**Comment by RandomTannenbaum** [comment]
**Stand 10.11.2023**
- Die Funktionen um Keyresults zu erstellen in Cypress Methoden ausgelagert
- Je einen Test geschrieben für die scoring Komponente, der jeweils ein Keyresult und dann darauf ein checkin erstellt.
- Was noch fehlt:
- Evtl. keyresult Methoden so anpassen dass ausser dem Titel noch weitere Werte mitgegeben werden können
- Den Wert des scoring components validieren. Ich habe hier versucht die width herauszulesen, diese wurde jedoch komischerweise immer als 0 zurückgegeben.
- Wie schon gesagt den Wert des scoring components validieren auf overview sowie auf detail ansicht.

**Comment by RandomTannenbaum** [comment]
Stand 14.11.2023
- Ich habe den Test für ein metrisches Keyresult parametrisiert.
- Methode im Test erstellt, die den Farbwert des scoring-components überprüft.
- Methode im Test erstellt, die die Breite des scoring components mit der breite des parents vergleicht und überprüft ob diese korrekt ist.

- Was noch fehlt:
- Die Überprüfungen müssen noch für den ordinal-test implementiert werden, also die Breite und Farbe. Die Farbe sollte kein grösseres Problem sein, jedoch weiss ich noch nicht ganz wie ich es für die Breite implementieren würde mit möglichst wenig redundanz. Es sollte jedoch nicht so schwer sein, da die spans im component entweder 100% oder 0% Breite haben, da das Keyresult ja ordinal ist.
- Es muss noch überprüft werden, ob der Stern bei einem moonshot ausgefärbt wird.
- Ich habe zwar auf die Farbe des components überprüft, jedoch muss noch getestet werden, ob bei einem moonshot der Hintergrund diese Sternchen hat, da dies nicht über die background color implementiert ist.

Mir ist noch aufgefallen, dass die Tests anscheinend so viel resourcen kosten, dass Cypress manchmal einfach abstürzt bei der Ausführung.
