### ISSUE TITLE
E2E Test Tab

### ISSUE THREAD

**Issue by lkleisa** [puzzle/okr#553]
Teste die Tab Funktion im gesamten OKRT

### Info
- Das Tabbing funktioniert nur im Chrome browser
- Es gibt schon ein Beispiel Test

### Todo
- [x] Teste das Tabbing überall
  - [x] Schau, dass das Richtige angewählt wird
  - [x] Schau, dass man Input mit Tabbing anwählen kann und etwas reinschreiben kann

Dabei sind pro flow die folgenden Punkte zu beachten:
- [x] Darstellung der einzelnen Komponenten entsprechen dem Figma
- [x] Werden die Richtigen aktionen aufgerufen
- [x] Haben die Buttons die korrekte funktionalität
- [x] Werden die richtigen Dialoge geöffnet

### Vorgehen
- [x] Das beispiel zum Tab E2E Testing von @kcinay055679 anschauen und sich mit den Methoden bekannt machen.
- [x] Nocheinmal in erinnerung Rufen, welche Elemente alles Tabbable sein sollten
- [x] Folgende Elemente sollten getestet werden:
  - [x] Hilfe Link
  - [x] User Menü
  - [x] Quartal Filter
  - [x] Objective Suche
  - [x] Team Filter
  - [x] Objective(s) & Objective-Detail
  - [x] Keyresult(s) & Keyresult-Detail
  - [x] Drei Punkte Menü:
    - [x] Objective bearbeiten & dialog
    - [x] Objective duplizieren & dialog
    - [x] Objective abschliessen & dialog
  - [x] Keyresult hinzufügen button & dialog
  - [x] Objective hinzufügen button & dialog
  - [x] Sämtliche Workflows Erstellen, bearbeiten, löschen usw ebenfalls mit Tab Testen.
- [x] Tests runen lassen
- [x] Falls nötig anpassen
- [x] Review von Jannik, Marc, Yanick oder Lias
- [x] Evtl changes nach dem Review & Code cleanup
- [ ] Review
- [ ] Merge

**Comment by ManuelMoeri** [comment]
*Stand 08.11.2023*

Zuerst das grundsätzliche. Falls jemand am Ticket weiterfahren sollte hat @kcinay055679 ein paar Beispiel-Tests zum Tabbing geschrieben. Dies sind die obersten *3* Tests. Sind ausserdem auskommentiert.

Grundsätzlich sind alle Tests schon vorhanden aber haben zum Teil noch keinen Inhalt. Falls ich einen Test vergessen habe Bitte hinzufügen. Ausserdem sind alle Tests ohne brauchbaren Body auskommentiert.

Beim test `it('Tab to quarter filter, objective filter and teamfilter in filters'` sollte noch geschaut werden ob das ausklappen des Quarterfilters und das an- oder abwählen des Teamfilters auch getestet werden sollte. Beim Objectivefilter ist eine Prüfung vorhanden die versucht 'Objective' hineinzuschreiben.

Sollten Fragen auftauchen einfach Bitte:
- Anrufen
- Auf PChat schreiben
- Privat schreiben
- Whatever solange es mich erreicht.

**Comment by ManuelMoeri** [comment]
*Stand 15.11.2023*

Das gute zuerst, alle Tests sind vorhanden. Der test `it ('Edit ordinal check-in with tab')` hat noch keinen Inhalt aber es gibt schon einen der das Metrische editiert darum sollte es nicht so schwierig sein diesen zu Implementieren.

Ausserdem habe ich bei 4 Testen einen Kommentar geschrieben der folgendes sagt "Unterscheidung zwischen metric und ordinal muss noch gemacht werden". Das heisst das die Tests grundsätzlich Funktionieren aber noch einen Entscheidenden fehler haben. Die Tests heissen: `Create metric check-in with tab`, `Create ordinal check-in with tab`, ` Edit metric check-in with tab` & `Edit ordinal check-in with tab`. Von diesen 4 Tests werden nämlich immer nur 2 Korrekt ausgeführt. Entweder die metrischen oder die ordinalen. Der Grund dafür ist ganz Simpel. Diese Tests erstellen/bearbeiten immer nur die Check-ins für das OBERSTE key result. Es muss einen Weg geben die Unterscheidung von einem Metrischen zu einem Ordinalen Key result sauber durchzuführen und Cypress damit sagen das er zum nächsten Key Result weiterspringen soll um dieses auch wieder auf Metrisch/ordinal zu prüfen.

Meine Idee zu diesem Problem wäre wie folgt.
Vor diesen 4 Tests die noch nicht ganz Komplett sind, werden mit einem anderen Test ein Metrisches und ein Ordinales Key Result mit den Namen "KeyResult metric by Cypress" & "KeyResult ordinal by Cypress" erstellt. Dann würde ich versuchen mit .focus() so lange zu Tabben bis ihr diese Namen in einem Key result titel findet. Der Vorteil des Verwendes von den Key Results die beim Test erstellt werden ist das diese Egal auf welcher DB immer vorhanden sind weil sie direkt vorher erstellt werden. Wenn diese Tests fertig sind sollte das Ticket abgeschlossen sein.

Folgendes noch:
Für das Schliessen der Dialoge entweder mit "Abbrechen" oder mit dem Kreuz existieren zwei Tests + eine Methode die genau das mit dem schliesssen macht. Ich habe dies nur einmal getestes weil es überall das gleiche Layout ist. Falls dies aber überall verlangt wäre müsse man einfach den Dialog aufmachen und dann die Methoden "closeDialogWithcloseButton()" oder "closeDialogWithCross()" im entsprechenden Test aufrufen und es wäre fertig.

Klingt sehr kompliziert und ist es zu einem gewissen Grad auch.

Sollten Fragen auftauchen einfach Bitte:
- Lias fragen (Ich habe ihm das problem kurz erklärt vielleicht kann er euch helfen)
- Anrufen
- Auf PChat schreiben
- Privat schreiben
- Whatever solange es mich erreicht.
