### ISSUE TITLE
Dialoge Allgemein Styling

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#581]
Als User möchte ich, dass alle Dialoge einheitliches Styling aufweisen. 

### Anforderungen
- [ ] Dialoge sind in der mobilen Ansicht full screen modale
- [ ] Wenn ein Dialog Scrollable ist, so ist der Titel des Dialogs und die Buttons immer sichtbar nur der Inhalt wird gescrolled
- [ ] Wenn Fehler angezeigt werden ist der Fokus automatisch auf dem Fehlerhaften Feld. 
- [ ] Alle Einzüge sind Einheitlich
- [ ] Alle Darstellenden Texte haben einen grauen Hintergrund ohne Rand

### Akzeptanzkriterien
- [ ] Die oben genannten Styles sind einheitlich über alle Dialoge implementiert
- [ ] End To End Tests stellen sicher, dass die Vorgaben erfüllt sind 
- [ ] Smoketests wurden gründlich durchgeführt
- [ ] Unittests sind wo nötig ergänzt.

**Comment by lkleisa** [comment]
### Abklären
- [ ] Objective: Muss Team auch Grau hinterlegt werden?

**Comment by lkleisa** [comment]
## Stand Montag Abend
- Die Einzüge sollten nun überall stimmen
- Die meisten Dialoge sind auf Mobile full screen eingestellt

### Todo
- [ ] Beim Scrolling in einem dialog soll header und footer einen shadow bekommen, so etwas hier -> https://css-tricks.com/books/greatest-css-tricks/scroll-shadows/
- [ ] Der Confirm dialog und check-in-history-dialog sollten noch full screen gemacht werden auf mobile
- [ ] Objective form: Beim edit stimmt alles, beim create ist der titel des dialogs über dem close icon
- [ ] Tests von KeyResult-Form und KeyResult-Dialog fixen

### Wichtig
Schauen dass alles auf handy, ipda und desktop stimmt

**Comment by MarcEgliP** [comment]
# Stand des Tickets
- Alle offenen TODOs, ausgenommen der Scrollschatten wurden abgehakt
- Das Check-In sowie die Check-In History kann nun auch auf Mobile gescrolled werden und passt sich dem Bildschirm an
- Die Einzüge wurden gefixed

# Was noch gemacht werden muss
- Über alles drüberschauen und überprüfen wo noch etwas ergänzt werden muss
- MEINER MEINUNG NACH: Scrollschatten weglassen. Sobald man den Scrollschatten einfügt, verschwindet er wieder, wenn man z.B. die Check-In history scrolled, da die Hintergrundfarbe der CheckIns den Scrollschatten überdeckt
