### ISSUE TITLE
E2E Test Team verwaltung

### ISSUE THREAD

**Issue by lkleisa** [puzzle/okr#585]
Teste die Funktionalitäten von der neuen Team verwaltung

### Todo
- [x] Ein neues Team kann einer Organisation aus dem LDAP zugeordnet werden
- [x] Bei einem Team kann die Organisation geändert werden 
- [x] Falls die zugehörige Organisation gelöscht werden sollte, wird dies im UI dargestellt

Dabei sind pro flow die folgenden Punkte zu beachten:
- [x] Darstellung der einzelnen Komponenten entsprechen dem Figma
- [x] Werden die Richtigen aktionen aufgerufen
- [x] Haben die Buttons die korrekte funktionalität
- [x] Werden die richtigen Dialoge geöffnet

### Vogehen
- [x] E2E Tests durchlesen, Vorstellung davon kriegen
- [x] Beginn mit der Implementierung der e2e-Tests, dabei werden
folgende Workflows getestet:
- [x] Teamdialog über das Icon im Header öffnen
- [x] Erstellung eines neuen Teams (Teamname definieren, Organisationen dazu auswählen)
- [x] Bearbeitung eines Teams (Teamname umschreiben, Organisationen abwählen + hinzufügen
