### ISSUE TITLE
Keyresults Duplizieren

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#614]
Als User möchte ich beim Duplizieren von Objectives auswählen, welche Key Results mit dupliziert werden.

### Anforderungen
- Im Dialog zum Duplizieren von Objectives kann neu auch ausgewählt werden, welche Key Results mit dupliziert werden
- Eine Liste der bestehenden KR Titeln ist im Dialog enthalten 
- Aus dieser Liste können mehrere Key Results ausgewählt werden.  Default mässig sind alle KR ausgewählt.
- Der Titel dieses Abschnitts wird eine Frage, "Welche Key Results sollen dupliziert werden?"
- Mit UX absprechen, wie der Dialog neu aussehen soll.

### TODO (Stand 09.12.2024)
- [x] Failenden Controller-Test fixen
- [x] Kontrollieren das für sämtlichen neuen Code Tests vorhanden sind.
    - [x] Controller-Tests
    - [x] Service-Tests
    - [x] E2E-Tests
- [ ] Cleanup des codes
- [ ] Review

### Akzeptanzkriterien
- [ ] Die Anforderungen sind erfüllt
- [ ] Smoketests wurden gründlich durchgeführt
- [ ] Unittests, Integrationstests, E2ETests sind ergänzt

**Comment by nevio18324** [comment]
### Todo's ###
- [ ] Feature umsetzten
- [ ] Unit-tests Integration-Tests und E2E Tests erstellen um das Feature voll zu testen
- [ ] Smoketesten

**Comment by nevio18324** [comment]
### Stand 26.11 ###
Das auswählen der Keyresults beim duplizieren funktioniert, jedoch failen viele Tests noch vor allem im backend unittest

**Comment by ManuelMoeri** [comment]
### Stand 29.11.2024
Heute habe ich eine offene Bugs beim duplizieren gefixt. Ausserdem habe ich (fast) alle Tests gefixt. Dann ist mir noch aufgefallen das einen komisches behaviour beim E2E-Testen gab. Dort habe ich schlussendlich noch die TestDaten angepasst da sie schlicht und einfach falsch waren. Ein kleines cleanup habe ich Heute auch schon gemacht musste es jedoch reverten da es ein feature kaputt machte.

**ToDo nächste Woche**
- [ ] Cleanup des Codes, zum Teil noch unverständlich
- [ ] Tests im backend laufen jedoch gibt es noch errors -> fixen
- [ ] Unit Test & E2E Tests ergänzen
- [ ] Smoke Testen lassen
- [ ] Mergen

**Comment by nevio18324** [comment]
### Stand 3.12 ###
Ich habe probiert die Objectivetests welche faileten zu reparieren dies ist auch gelungen, dannach wollte ich den shouldReturnIsCreatedWhenObjectWasDuplicated anpassen da sich die DuplcateObjective schnittstelle verändert hat.
Dabei ist folgendes Problem aufgetreten und zwar versendet MockMvc den request mit dem 
Content-Type: applicationjson;charset=UTF-8
wodurch ich diese Response erhalten habe
```
status = 415
Error message = Content-Type 'application/json;charset=UTF-8' is not supported.
Headers = [Accept:"application/json, application/yaml, application/*+json", X-Content-Type-Options:"nosniff", X-XSS-Protection:"0", Cache-Control:"no-cache, no-store, max-age=0, must-revalidate", Pragma:"no-cache", Expires:"0", X-Frame-Options:"DENY"]
```
Was Ich bereits probiert habe/werde:
- [x] MockMvc Javadoc durchgelesen ob ich dort etwas zu diesem Behaviour finde dadurch habe ich das gefunden was im Zusammenhang stehen könnte jedoch bezweifle ich es![Image](https://github.com/user-attachments/assets/c6dd67d3-cd88-4cd8-a511-fc3c780e46ca)
- [x] Den body einer funktionierenden Frontend anfrage benutzt um zu testen ob das behaviour am body liegt (War nicht der Fall)
- [x] [Stackoverflow frage](https://stackoverflow.com/questions/79247709/mockmvc-perform-with-contenttype-application-json-but-then-makes-request-using-a) eröffnet
