### ISSUE TITLE
Header Mobile

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#623]
Zur Zeit ist der Header auf der mobilen Ansicht noch nicht sauber.

### Anforderungen
- Der Header entspricht der neuen Vorlage von [UX](https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=3009-1005&node-type=canvas&t=HJRRh2ZmSQTaARyv-0)
- [Problem](https://github.com/orgs/puzzle/projects/3/views/1?filterQuery=milestone%3A%22UX+%C3%9Cberarbeitung+und+Bug+Fixing%22&pane=issue&itemId=75329945) ist behoben.

### Akzeptanzkriterien
- [x] Der Bug mit den verschiedenen Bildschirmgrössen ist behoben und der Header ist stabil nach den neuen vorgaben von UX
- [x] Testing ist ergänzt.

**Comment by RandomTannenbaum** [comment]
Needs to be rebased and there seem to be bugs that need to be addressed -> see pr.

**Comment by ManuelMoeri** [comment]
### Stand 13.11.2024

**Erledigt**
Ich habe heute und in den letzten Tagen einiges an dieser PR erledigt. Unteranderem habe ich einige bugs gefixt die noch auftratten. Ich habe ausserdem ein Feature das von Paco requested wurde hinzugefügt. Grundsätzlich sorgt es dafür das die im moment ausgewählten Teams bei dem Teamfilter immer an erster stelle erscheinen. Sobald die Teams wieder abgewählt werden, werden sie wider in ihre alte Alphabetische Reihenfolge zurückversetzt. Dies ist nötig das die gerade ausgewählten Teams bei dem Mobile header nicht unter die 'Mehr' option rutschen.
> [!CAUTION]
> Im Moment has es noch immer einen bug der behoben werden muss.

**Bug**
Im moment gibt es noch immer das Problem das nicht alle Teams auf der Overview bei einem grossen Screen angezeigt werden. Dies passiert weil die Logik in dem `team-filter.component.html` maximal 6 Teams anzeigt und dann den 'Mehr' bzw. 'Weniger' button rendered. Dieser button wird jedoch natürlich nur auf der Mobile ansicht angezeigt. Auf der grossen Ansicht nicht. Es muss noch ein weg gefunden werden das die Logik des Aufteilen der Teams nicht auf dem grossen Screen geschieht.

**ToDo**
- [ ] Den beschriebenen bug fixen
- [ ] Tests ergänzen & fixen
- [ ] Alles nocheinmal gründlich smoke testen (lassen)
