### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#727]
Als User möchte ich die Möglichkeit OKRs für ein quartal, welches weiter in der Zukunft ist als ein Quartal bereits zu draften. 

### Anforderungen
- Zu den 6 Quartalen, welche zur Zeit angezeigt werden existiert zusätzlich ein Backlog
- Der Backlog wird wie ein eigenes Quartal behandelt
- Ich kann Objectives als Draft im Backlog erfassen --> nur Draft?
- Der Backlog kann immer angewählt werden und hat kein Start oder Enddatum.
- Objectives aus dem Backlog können ganz normal in ein Quartal verschoben werden

### Akzeptanzkriterien
- [x] Die Anforderungen sind alle erfüllt
- [x] Smoketests wurden gründlich durchgeführt
- [x] Neue E2E Testsuite für den Backlog ist erstellt
- [x] Unit- und IT-Tests sind geschrieben

### TODO 
- [x] Migrationskript
- [x] Backlog immer nach vorne liefern
- [x] Check für Quarter start / end date nie null
- [x] In frontend einbauen
- [x] Confirm Toaster mit Nachricht "Objective als Draft im Backlog gespeichert". 
- [x] Check für nur Draft Objectives in dieses Quarter
- [x] Backend testing
- [x] Frontend unit testing
- [x] Frontend e2e testing
- [x] Don't use id 999 for check on backlog
- [x] Wenn ein Objective im Backlog erstellt wird, sollte nur der Als Draft speichern Button vorhanden sein
- [x] Ein Objective welches sich im Backlog befindet, sollte via 3 Punkte Menü veröffentlicht werden können --> Auswahl nur aus "richtigen Quartern"
- [x] Ein bereits veröffentlichtes Objective sollte ins Backlog verschoben werden können, dabei wechselt sich der Status zu Draft, abgeschlossene Objectives können nicht in den Backlog verschoben werden
- [x] Regex zum überprüfen ob Backlog oder Quartal
- [x] ValidationService benützen in QuarterBusinessService
- [x] Beim bearbeiten soll bei OnGoing auch Backlog sein und der submit Button soll nicht verschwinden
- [x] Fix tests
- [x] Make code cleaner

**Comment by RandomTannenbaum** [comment]
**Stand 16.01.2024**
Es wurde ein neuer Branch names `feature/727-backlog` erstellt. Auf diesem habe ich, um später ein Quarter ohne Datum erstellen zu können, begonnen die NotNull constraints auf dem model im Backend und auf der DB mit ein Migrationsskript zu entfernen.

Momentan funktioniert das Migrationsskript aus mir unerfindlichen Gründen leider noch nicht, weshalb dies noch gefixt werden muss.
