### ISSUE TITLE
Das Plus Zeichen ist nicht in Balance

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#731]
Das Plus Zeichen auf den Hinzufügen Buttons ist nicht in Balance mit der Schrift 

### Anforderungen
- Mit Ux abklären, wie das Pluszeichen plaziert werden muss, damit die Balance stimmt
- Abklären ob das Plus wirklich notwendig ist.
- Vorschlag: Das Pluszeichen ist mittig zum Grossbuchstaben und genau gleich hoch wie der folgende Grossbuchstabe
- Der Abstand zwischen Pluszeichen und Text etwas kleiner

### Akzeptanzkriterien
- [ ] Die Anforderungen sind erfüllt
- [ ] Smoketests sind gründlich durchgeführt
- [ ] PO und UX haben die Story beide abgenommen 
- [ ] Falls notwendig sind die Tests ergänzt 

### ToDo
- [x] Abklären [wie](https://tex.stackexchange.com/questions/567250/always-raise-plus-sign-in-text)  das Pluszeichen platziert werden muss -> Ein bisschen höher als der Text
- [x] Abklären ob das Plus notwendig ist -> Es ist notwendig
- [x] Den Abstand verringern
- [x] Feedback PO
- [x] Allfällige Änderungen
  - [x] Abstand vergrössern
  - [x] Pluszeichen und Text gleichgross machen
  - [x] Schatten beim Add Keyresult button fixen
- [x] Feedback UX
- [x] Anfalldende Änderungen
  - [x] Pluszeichen 0.05 rem kleiner
  - [x] Pluszeichen 1px nach oben schieben
- [x] Änderungen mit PO anschauen
- [x] Tests (falls nötig)
- [x] Review @kcinay055679 oder @MarcEgliP 
- [x] Anfallende Änderungen
  - [x] -
- [ ] Review
- [ ] Feedback Review implementieren
- [ ] Merge

**Comment by ManuelMoeri** [comment]
### Stand 22.01.2023

Die Anforderungen wurden grundsätzlich erfüllt. Das SVG wurde ersetzt da das alte einen zu grossen Rand hatte. Der Abstand zwischen SVG und Text wurde verringert und besser alignet. Das Kurze approvment von Tobias wurde auch schon eingholt. Sämtliche änderungen wurden im voraus mit UX besprochen.

**Todo**
- [ ] Approval Simu
- [ ] Approval PO
