### ISSUE TITLE
Archivierungsfunktion

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#843]
Als User der Applikation möchte ich die Möglichkeit haben, auch OKRs einzusehen, welche nicht in den aktuellen Quartalen stattgefunden haben.

### Anforderungen
- Zusätzlich zu den Quartalen und dem Backlog existiert im Quartal Dropdown ein Archiv
- OKRs welche nicht mehr in den angezeigten Quartalen sind, werden ins Archiv verschoben
- OKRs welche im Archiv sind, haben ein `archived` flag gesetzt.

### Akzeptanzkriterien
- [ ] Die Story ist wie beschriben umgesetzt
- [ ] Unit-, Integrations, und E2E-Tests sind ergänzt.
- [ ] Für die DB ist ein Migrationsskript erstellt.

**Comment by lkleisa** [comment]
# TODO 

- [ ] Handhabung archived Flag auf dem Objective im Frontend betrachten (bis jetzt gar nicht im Model im Frontend)
- [ ] Frontend Testing
- [ ] Backend Testing
