### ISSUE TITLE
#okr Objektive Abschluss Kommentar anzeigen

### ISSUE THREAD

**Issue by kcinay055679** [puzzle/okr#863]

**Comment by peggimann** [comment]
> [!TIP]
> Jean-Claude hat bereits coole Vorarbeit geleistet siehe: https://github.com/puzzle/okr/pull/1192#issue-2679354925

**Comment by Miguel7373** [comment]
### Todo

- [ ] Tip Lesen
- [ ] Get für Completed schrieben
- [ ] Backend Tests
- [ ] Die von dem backend gesendeten daten empfangen und am richtigen Ort anzeigen ([Figma](https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=3068-1995&t=HJRRh2ZmSQTaARyv-4))
- [ ] Frontend Unit Tests
- [ ] Cypress Tests

**Comment by Miguel7373** [comment]
### Stand 7.1.2025

Ich habe im Backend den Endpoint geschreiben und im Frontend implementiert das es Angezeigt wird wenn es einen Kommentar hat. Ebenfalls habe ich ein wenig bei den Cypress tests gemacht weis aber nicht ob das ausreicht oder ob es noch einen eingenen Test nötig hat.

**Comment by Miguel7373** [comment]
### Stand 9.1.2025

Ich habe heute das Ticket so weit fertig gemacht es muss nun noch ein Peer review durchgefürt werden so wie  noch kurz das Wording (Abschlusskommentar) mit Pippo abgesprochen werden.
