### ISSUE TITLE
Check-in soll die Möglichkeit bieten eine neue Action für ein Key Result zu erfassen

### ISSUE THREAD

**Issue by peggimann** [puzzle/okr#888]
Als Anwender der OKR habe ich oft den Fall, dass ich bei einem Check-in bestehende Actions erledigt habe und die Massnahmen neue Actions sind. Daher möchte ich die Möglichkeit im Check-in  Prozess eine neue Action für das Key Result zu erfassen. 

### Anforderungen
- Auf dem Check-in wird das Feld Massnahmen entfernt
- Neu existiert auf dem Check-in, wo ursprünglich das Feld Massnahmen war, die Möglichkeit neue Actions zu erfassen : https://www.figma.com/design/xjjJGiSS276lhesXpYy6ml/OKR-Tool-Puzzle?node-id=3073-21839&t=WXdPVJZadvHnWlgU-4

### Akzeptanzkriterien
- [ ] Check-in hat kein Feld "Massnahmen" mehr
- [ ] Check-in hat ein neues Feld "Weiter Actions"
- [x] (Im Bearbeitungsmodus hat es einen Button "Speichern", der diesen beendet und es erlaubt die Actions auch wieder auszuwählen)
- [x] Es können mehrere oder keine Actions erfasst werden
- [x] Design entspricht den Mockups

**Comment by RandomTannenbaum** [comment]
**ToDo**
- [ ] Feld Massnahmen von Check-In Dialog und model entfernen
- [ ] DB-Migration schreiben um Feld zu entfernen
- [ ] Unter Action-Plan items auf dem Dialog den neue Action button anzeigen
- [ ] Wenn der button ausgewählt wird, den action plan component und einen speichern button anzeigen
- [ ] Nach dem Speichern werden die alten und neuen actions angezeigt und man kann sie über die checkboxen auswählen

**Comment by RandomTannenbaum** [comment]
**Fragen**:
Soll das Feld "Massnahmen" nur vom Dialog entfernt werden, oder soll es auch vom Model entfernt werden. Soll dabei auch bei allen bestehenden records die Spalte Massnahmen entfernt werden?

**Comment by RandomTannenbaum** [comment]
**Stand 07.01.2025**
Ich habe das Feld "Massnahmen" aus dem Dialog zu entfernt. Ausserdem habe ich die Logik geschrieben, so dass man nun eine oder mehrere Actions hinzufügen und dann auch speichern kann. Zudem habe ich noch einen I18n bug im confirm Dialog bei den Actions gefixt.

**Comment by RandomTannenbaum** [comment]
**Stand 08.01.2025**
Heute habe ich das Styling soweit beendet. Das Plus ist kleiner als im Figma, da es so aussehen soll wie im Rest der Applikation. Eventuell muss noch der Style des speichern buttons angeschaut werden, da dieser im Figma nicht vorhanden ist.

Die Funktionalität ist auch soweit fertiggestellt. Ein Edge-Case existiert hier noch. Grundsätzlich werden leere actions nicht gespeichert. Dieses Verhalten habe ich auch bei mir so übernommen. Wenn man ein keyresult bearbeitet, bei einer action den Text komplett löscht und diese dann speichert, dann wird diese action nicht gelöscht sondern so belassen wie sie vorher war. Wenn man bei meinem Bearbeitungsfenster die actions bearbeitet und eine leert, dann verschwindet diese nach dem vorläufigen Speichern im check-in dialog. Wenn man jedoch das Check-In dann speichert, dann ist die action noch vorhanden. Es verhält sich also auch hier so wie beim bearbeiten des Key-Results.

2 Möglichkeiten:
- Wenn man actions leert, dann werden sie gelöscht. Sowohl beim check-in erstellen als auch beim key-result bearbeiten.
- Wenn man eine neue action erstellt und eine alte dabei leert im check-in Dialog, dann muss diese direkt nach dem vorläufigen speichern wieder erscheinen.
