### ISSUE TITLE
CheckIn Autor in der CheckIn-History

### ISSUE THREAD

**Issue by lkleisa** [puzzle/okr#925]
Als Benutzer möchte ich sehen könne, welche Person welches CheckIn erfasst hat. Dazu soll die CheckIn-History mit dem Autor (createdBy) ergänzt werden. 
Zusätzlich sollte der ganze Komponent überarbeitet werden um 1:1 wie das Figma auszusehen  da z.B. derzeit der Abstand zwischen Veränderungen und dem Text nicht stimmt.
In der Applikation soll dies wie folgt aussehen:

![Image](https://github.com/puzzle/okr/assets/68543649/e960110b-22db-47fc-9bc0-5d3a49caaa20)

Bei Fragen auf Phillip Leimgruber oder Simon Hirsbrunner zugehen

### Anforderungen
- Die Abstände, Textgrössen. Textgewichte usw. im Komponent entsprechen dem Figma 
- Die CheckIn-History zeigt welche Person ein CheckIn erfasst hat

### Aktzeptanzkriterien
- [x] Frontend-Test wurden ergänzt (Unit und E2E falls nötig)
- [x] Backend-Test wurden ergänzt 
- [x] Der Author wird in der CheckIn-History korrekt angezeigt
- [x] Das ganze wurde vom UX approved.

**Comment by nevio18324** [comment]
### Todo's ###
- [ ] Figma vom UX anschauen
- [ ] Autor zum Component hinzufügen
- [ ] Andere kleine details im Figma auf den Component übertragen
- [ ] Kurz mit dem UX absprechen ob der Component so für sie passt

**Comment by nevio18324** [comment]
### Stand 9.1 ###
Ich habe den Komponent dem Figma angepasst und werde ihn am 14.1 noch Jürgen und Simon zeigen
