### ISSUE TITLE
[cleanup, refactoring] DTO Umbenennung value -> zone

### ISSUE THREAD

**Issue by clean-coder** [puzzle/okr#937]
In den beiden DTOs (im Server):
- `KeyResultLastCheckInOrdinalDto.java`
- `CheckInOrdinalDto.java`

gibt es jeweils ein "Property" `Zone value`, was nicht so schön ist. Besser wäre `Zone zone`. Die Umbenennung im Server führt dazu, dass die Cypress Tests rot werden, da es im Client auch entsprechende Modell Klassen gibt, die auch `Zone value` verwenden.
- `CheckIn.ts`
- und ev. noch mehr

`Zone zone` wäre schöner, aber man muss das im Client und im Server gleichzeitig refactoren.

### Anforderungen
- Die Properties im Backend heissen neu `zone`, um sie sprechender zu machen
- Das Frontend wird so angepasst, wie nötig

### Aktzeptanzkriterien
- [x] Das Property in `KeyResultLastCheckInOrdinalDto.java` wurde umbenannt
- [x] Das Property in `CheckInOrdinalDto.java` wurde umbenannt
- [x] Die Properties im Frontend wurden umbenannt (z.B. in `CheckInMin.ts` und `CheckIn.ts`
- [x] Unit und E2E-Tests wurden angepasst falls nötig

**Comment by clean-coder** [comment]
In den beiden DTOs (im Server):
- `KeyResultLastCheckInOrdinalDto.java`
- `CheckInOrdinalDto.java`


gibt es jeweils ein "Property" `Zone value`, was nicht so schön ist. Besser wäre `Zone zone`. Die Umbenennung im Server führt dazu, dass die Cypress Tests rot werden, da es im Client auch entsprechende Modell Klassen gibt, die auch `Zone value` verwenden.
- `CheckIn.ts`
- und ev. noch mehr

`Zone zone` wäre schöner, aber man muss das im Client und im Server gleichzeitig refactoren.

**Comment by Miguel7373** [comment]
### Todo

- [x] Rename value to zone in Backend
- [ ] Create new models for metric and ordinal CheckIn's
- [ ] Change logic so it works like the keyResult's

**Comment by Miguel7373** [comment]
### Stand 26.11.2024

Das Grundprinzip funktioniert. Ich habe es nun mit mehreren Models im Frontend gelöst und dann die Logik so angepasst, dass es überall wieder richtig funktioniert und unterscheidet, ob es metric oder ordinal ist (nur wo es nötig was)


Still ToDo

- [ ] Tests auf der Pipe zum Laufen bringen (lokal funktionieren sie)
- [ ] Im Hintergrund wird der Streifen, ob es im Fail Commit oder Target Bereich ist, noch nicht angezeigt (nur bei ordinalen)
- [ ] Generelles code clean up, da es noch ein bisschen Buggy scheint.

**Comment by Miguel7373** [comment]
Stand 26.11.2024

Das Ticket ist nun fast fertig die funktionen laufen alle wieder.

Still ToDo:
- [ ] Das Parsing in den files im frontend ist eventuell an manchen stellen unnötig
- [ ] Die Edit Tests im `key-result.cy.ts` file failen alle noch
- [ ] Frontend Untit test laufen noch nicht die müssen noch an die neue logik angepasst werden
- [ ] Peer Review
